merge_queue:
  max_parallel_checks: 2
  
queue_rules:
  - batch_size: 3
    batch_max_wait_time: 20 sec
    merge_method: squash
    name: default
    queue_conditions:
      - status-success = Explore-GitHub-Actions
    merge_conditions:
      - check-success = Explore-GitHub-Actions
