merge_queue:
  max_parallel_checks: 3
  
queue_rules:
  - batch_size: 3
    merge_method: squash
    name: default
    queue_conditions:
      - and:
        - "#approved-reviews-by >= 1"
        - status-success = Explore-GitHub-Actions
    merge_conditions:
      - check-success = Explore-GitHub-Actions
